[package]
name = "guillotiere-mayhem-fuzz"
version = "0.0.0"
publish = false
edition = "2018"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
arbitrary = { version = "1", features = ["derive"] }

[dependencies.guillotiere]
path = "../.."

# Prevent this from interfering with the root workspace
[workspace]
members = ["."]

[[bin]]
name = "alloc_dealloc"
path = "fuzz_targets/alloc_dealloc.rs"
test = false
doc = false

[profile.release]
debug = 1
